title: Sara Abdelazim
logo: /assets/img/SaraPhoto.jpeg
description: Data Scientist / Data Analyst 
#link: [data science portfolio](https://sarax0.github.io/portfolio/data-science)
#show_downloads: true
theme: jekyll-theme-minimal
